repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
  - repo: local
    hooks:
      # - id: local-precommit
      #   name: local pre-commit tasks
      #   description: Runs local pre-commit tasks.
      #   entry: bash -c 'deno run --unstable --allow-all pre-commit.ts; git add -u' --
      #   always_run: true
      #   pass_filenames: false
      #   language: system
      - id: lint-check
        name: lint check
        description: Lint JavaScript/TypeScript source code.
        entry: yarn lint
        types_or: [javascript, jsx, ts, tsx, json, markdown]
        pass_filenames: false
        language: system
      - id: test
        name: test
        description: Run tests using the test runner.
        entry: yarn test
        types_or: [javascript, jsx, ts, tsx, json]
        pass_filenames: false
        language: system
